import { build } from "esbuild";
import path from "path";
import { readFileSync } from "fs";

// Read package.json to externalize all npm dependencies
const pkg = JSON.parse(readFileSync("package.json", "utf-8"));
const external = [
  ...Object.keys(pkg.dependencies || {}),
  ...Object.keys(pkg.devDependencies || {}),
];

await build({
  entryPoints: ["src/server-entry.ts"],
  bundle: true,
  platform: "node",
  target: "node20",
  format: "esm",
  outfile: "api/_bundle.mjs",
  alias: { "@": path.resolve("src") },
  // Keep npm packages external — Vercel NFT will trace them
  external,
  loader: { ".json": "json" },
  banner: { js: "// Auto-generated by scripts/build-api.mjs — do not edit" },
});

console.log("✓ API bundled → api/_bundle.mjs");
