// Catch-all route for /api/* — Vercel's `api/` directory convention only routes
// /api to api/index.ts by default. The vercel.json rewrite forwards every
// /api/(.*) here, so all request handling lives in the bundled hono app.
// @ts-ignore — _bundle.mjs is generated by scripts/build-api.mjs at build time
export { default } from "./_bundle.mjs";
